import { useEffect } from "react";
import { EarlyAccessCtaSection } from "./sections/EarlyAccessCtaSection";
import LandingLayout from "@/layouts/LandingLayout";
import { scrollToSection } from "@/lib/utils";

export default function TermsOfServicePage() {
  const sections = [
    {
      title: "1. Acceptance of Terms",
      content:
        'By accessing or using the Sorene platform, website, or any associated services (collectively, the "Services") provided by Sorene, Inc., a Delaware corporation ("Sorene," "we," "us," or "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use our Services.\nThese Terms apply to all visitors, registered users, and others who access or use the Services. We may update these Terms from time to time; continued use of the Services after changes constitutes acceptance.',
    },
    {
      title: "2. Description of Services",
      content:
        "Sorene is an AI-powered platform designed to help career changers, aspiring entrepreneurs, and professionals find, plan, and launch businesses aligned with their skills, values, and lifestyle. Our Services include:",
      items: [
        'Psychometric and self-discovery assessments (the "Sorene DNA" profile)',
        "AI-generated business idea suggestions based on user profile data",
        "Business plan creation and structuring tools",
        "Execution roadmaps, educational resources, and community features",
        "Any additional features or tools we introduce over time",
      ],
    },
    {
      title: "3. Not Professional Advice",
      content: (
        <>
          <p className="font-semibold text-neutral-900 mb-2">
            IMPORTANT DISCLAIMER:
          </p>
          <p>
            The Services, including all assessments, business idea suggestions,
            business plans, financial projections, execution roadmaps, and any
            other outputs or recommendations generated by Sorene, are provided
            for informational and educational purposes only.
          </p>
          <p className="mt-4">
            Sorene is NOT a licensed business advisor, financial advisor,
            investment advisor, legal advisor, psychologist, or career
            counselor. Nothing on the platform constitutes professional
            business, financial, legal, psychological, or career advice.
          </p>
          <p className="mt-4">
            You should not make significant financial, business, career, or
            personal decisions based solely on information provided by Sorene
            without independently verifying that information and, where
            appropriate, consulting qualified professionals. Sorene makes no
            guarantee that any business idea, plan, or recommendation will
            result in success, revenue, or profitability.
          </p>
          <p className="mt-4 italic">
            Any reliance you place on the Services is strictly at your own risk.
          </p>
        </>
      ),
    },
    {
      title: "4. Eligibility and Account Registration",
      content:
        "You must be at least 18 years of age to use the Services. By using the Services, you represent that you are 18 or older and have the legal capacity to enter into these Terms.\nWhen you register for an account, you agree to provide accurate, current, and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately at contact@sorene.ai if you suspect any unauthorized use of your account.",
    },
    {
      title: "5. Subscription Plans and Payments",
      content:
        "Sorene offers the following subscription tiers: a free tier with limited access, a Starter plan, and a Professional plan. Pricing and features for each tier are displayed on our website and may change with notice.\nBy subscribing to a paid plan, you authorize us to charge your payment method on a recurring basis (monthly or annually, as selected). All fees are in U.S. dollars. You may cancel your subscription at any time; cancellation takes effect at the end of your current billing period and you will not receive a refund for the unused portion of any billing period, except as required by applicable law.\nWe reserve the right to modify pricing with at least 30 days' written notice to active subscribers.",
    },
    {
      title: "6. User Content and Data",
      content:
        'You retain ownership of any information, content, or data you submit to the Services ("User Content"), including your assessment responses, business plan inputs, and profile information. By submitting User Content, you grant Sorene a non-exclusive, worldwide, royalty-free license to use, process, and store such content solely as necessary to provide and improve the Services.\nYou agree not to submit User Content that is false, misleading, unlawful, infringing, or harmful. We reserve the right to remove User Content that violates these Terms.',
    },
    {
      title: "7. Intellectual Property",
      content:
        "All content, features, technology, and materials comprising the Services—including but not limited to software, algorithms, assessments, design, text, graphics, and the Sorene DNA profile methodology—are the exclusive property of Sorene, Inc. and are protected by applicable intellectual property laws.\nYou may not copy, modify, distribute, sell, or create derivative works from any part of the Services without our prior written consent. The Sorene name, logo, and brand marks are trademarks of Sorene, Inc.",
    },
    {
      title: "8. Prohibited Conduct",
      content: "You agree not to:",
      items: [
        "Use the Services for any unlawful purpose or in violation of any applicable laws or regulations",
        "Attempt to gain unauthorized access to any part of the Services or to other users' accounts",
        "Reverse engineer, decompile, or attempt to extract the source code of the platform",
        "Use automated tools, bots, or scrapers to access or collect data from the Services",
        "Submit false or misleading information through the platform",
        "Use the Services to harass, abuse, or harm other users",
        "Resell, sublicense, or commercialize any outputs of the Services without our written consent",
      ],
    },
    {
      title: "9. Limitation of Liability",
      content: (
        <>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SORENE, INC. AND
            ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE
            FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
            DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF DATA,
            BUSINESS INTERRUPTION, OR LOSS OF GOODWILL, ARISING OUT OF OR
            RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICES.
          </p>
          <p className="mt-4">
            SORENE'S TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING
            UNDER THESE TERMS SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU
            PAID TO SORENE IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR (B) ONE
            HUNDRED U.S. DOLLARS ($100).
          </p>
        </>
      ),
    },
    {
      title: "10. Disclaimer of Warranties",
      content:
        'THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. SORENE DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.',
    },
    {
      title: "11. Indemnification",
      content:
        "You agree to indemnify, defend, and hold harmless Sorene, Inc. and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising out of or related to: (a) your use of the Services; (b) your User Content; (c) your violation of these Terms; or (d) your violation of any third-party rights.",
    },
    {
      title: "12. Termination",
      content:
        "We may suspend or terminate your access to the Services at our discretion, with or without notice, for conduct that we determine violates these Terms, is harmful to other users, or is otherwise inappropriate. You may terminate your account at any time by contacting us at contact@sorene.ai.\nUpon termination, your right to use the Services ceases immediately. Sections that by their nature should survive termination (including Sections 3, 7, 9, 10, 11, 13, and 14) shall survive.",
    },
    {
      title: "13. Governing Law and Dispute Resolution",
      content: (
        <>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of the State of Delaware, without regard to its conflict of
            law principles. Any dispute arising under or related to these Terms
            shall be resolved by binding arbitration administered under the
            rules of the American Arbitration Association, except that either
            party may seek injunctive relief in any court of competent
            jurisdiction.
          </p>
          <p className="mt-4 font-semibold text-neutral-900">
            YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR
            CLASS-WIDE ARBITRATION.
          </p>
        </>
      ),
    },
    {
      title: "14. General Provisions",
      content: (
        <>
          <p>
            These Terms constitute the entire agreement between you and Sorene
            with respect to the Services and supersede all prior agreements. If
            any provision of these Terms is found to be unenforceable, the
            remaining provisions will continue in full force. Our failure to
            enforce any right or provision shall not constitute a waiver of that
            right.
          </p>
          <p className="mt-6">
            For questions about these Terms, contact us at:{" "}
            <span className="text-amber-500 font-medium">
              contact@sorene.ai
            </span>
          </p>
          <p className="mt-2 font-medium text-neutral-900">
            Sorene, Inc. | Incorporated in the State of Delaware, United States
          </p>
        </>
      ),
    },
  ];

  useEffect(() => {
    scrollToSection("header-logo");
  }, []);

  return (
    <LandingLayout>
      <div className="flex flex-col min-h-screen w-full bg-white items-center">
        <main className="w-full max-w-[1006px] px-6 py-16">
          {/* Header */}
          <div id="header" className="flex justify-center">
            <div className="mb-12 text-center">
              {/* Badge */}
              <div className="mb-6 flex justify-center">
                <div className="flex items-center justify-center rounded-full px-4 h-[36px] text-[13px] text-neutral-700 border border-neutral-200 bg-white">
                  Effective Date:
                  <span className="text-amber-400 ml-1 font-medium">
                    April 1, 2026
                  </span>
                </div>
              </div>

              {/* Title */}
              <h1 className="mb-6 text-[48px] lg:text-[64px] font-semibold text-neutral-900 tracking-tight">
                Terms of Service
              </h1>
            </div>
          </div>

          {/* Content */}
          <div className="space-y-12 text-left">
            {sections.map((section, index) => (
              <section key={index}>
                <h2 className="mb-4 text-[24px] font-semibold text-[#101010]">
                  {section.title}
                </h2>
                {typeof section.content === "string" ? (
                  <p className="text-[#878787] text-base leading-7 whitespace-pre-line">
                    {section.content}
                  </p>
                ) : (
                  <div className="text-[#878787] text-base leading-7">
                    {section.content}
                  </div>
                )}
                {section.items && (
                  <ul className="mt-4 space-y-3">
                    {section.items.map((item, idx) => (
                      <li
                        key={idx}
                        className="flex items-start gap-3 text-[#878787] text-base leading-7"
                      >
                        <span className="mt-2.5 h-1.5 w-1.5 shrink-0 rounded-full bg-neutral-400" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </section>
            ))}
          </div>
        </main>

        <EarlyAccessCtaSection />
      </div>
    </LandingLayout>
  );
}
